From ce4618c6f002776e499a223bcaad7c8f0e2d65db Mon Sep 17 00:00:00 2001
From: Sigmanificient <edhyjox@gmail.com>
Date: Fri, 3 Jan 2025 23:28:36 +0100
Subject: [PATCH] python312Packages.pyliblo: Fix build

---
 pkgs/development/python-modules/pyliblo/default.nix | 5 +++++
 1 file changed, 5 insertions(+)

diff --git a/pkgs/development/python-modules/pyliblo/default.nix b/pkgs/development/python-modules/pyliblo/default.nix
index 7caead892995a..88b3476686be0 100644
--- a/pkgs/development/python-modules/pyliblo/default.nix
+++ b/pkgs/development/python-modules/pyliblo/default.nix
@@ -23,6 +23,11 @@ buildPythonPackage rec {
       url = "https://git.alpinelinux.org/aports/plain/community/py3-pyliblo/py3.11.patch?id=a7e1eca5533657ddd7e37c43e67e8126e3447258";
       hash = "sha256-4yCWNQaE/9FHGTVuvNEimBNuViWZ9aSJMcpTOP0fnM0=";
     })
+    # Fix compile error due to  incompatible pointer type 'lo_blob_dataptr'
+    (fetchurl {
+      url = "https://github.com/s0600204/pyliblo/commit/ebbb255d6a73384ec2560047eab236660d4589db.patch";
+      hash = "sha256-KxvEwdDEeWkAdjJS61K0qRys08Unp9d1BbZK52YeWfY=";
+    })
   ];
 
   build-system = [ cython_0 ];